
install.packages("devtools")
library(devtools)

install_github("Vivianstats/scImpute")
install_github("mohuangx/SAVER@*release")

install.packages("Rtsne")

install.packages("scImpute")
install.packages("SAVER")
install.packages("Rtsne")
install.packages("preprocessCore")
install.packages("igraph")
install.packages("monocle")
install.packages("visNetwork")
install.packages("limma")
install.packages("edgeR")
install.packages("scde")
install.packages("sva")
install.packages("shiny")
install.packages("htmltools")
install.packages("shinyjs")
install.packages("htmlwidgets")
install.packages("plotly")
install.packages("fgsea")
install.packages("KEGG.db")
install.packages("GO.db")
install.packages("org.Hs.eg.db")
install.packages("org.Mm.eg.db")
install.packages("Rlof")
install.packages("scales")
install.packages("reshape2")
install.packages("purrr")
install.packages("readr")
install.packages("stringr")
install.packages("tidyr")
install.packages("tibble")
install.packages("forcats")
install.packages("dplyr")
install.packages("SummarizedExperiment")
install.packages("NMF")
install.packages("dplyr")
