echo -e "\033c"
echo "################################################################################"
echo "#                                                                              #"
echo "#             The Granatum server is now running from VirtualBox.              #"
echo -e "#       Now \e[2;30;47mopen a browser outside of VirtualBox\033[00m and set the address to        #"
echo "#                                                                              #"
echo "#                          http://localhost:8028                               #"
echo "#                                                                              #"
echo "#                  To stop the server, close this window.                      #"
echo "#                                                                              #"
echo "################################################################################"
